import type { Condition } from './types'

export const CATEGORY_LABELS: Record<string, string> = {
  houseplant: 'Houseplant',
  crop: 'Crop / garden',
  tree: 'Tree / woody',
  ornamental: 'Ornamental',
  dog: 'Dog',
  cat: 'Cat',
  livestock: 'Livestock',
  equine: 'Horse',
  bird: 'Bird',
  reptile: 'Reptile',
  'small-mammal': 'Small mammal',
}

export const CONDITIONS: Condition[] = [
  {
    id: 'plant-n-def',
    name: 'Nitrogen deficiency',
    commonName: 'General chlorosis of older leaves',
    kingdom: 'plant',
    categories: ['houseplant', 'crop', 'tree', 'ornamental'],
    type: 'deficiency',
    summary:
      'Nitrogen is mobile in the plant. When it runs short, chlorophyll is stripped from older foliage first, leaving a pale, even yellow while new growth stays greener.',
    visualSigns: [
      'Older, lower leaves uniformly pale yellow',
      'Stunted, spindly growth',
      'Smaller than normal leaves',
      'Premature drop of lower foliage',
    ],
    keywords: [
      'yellow', 'yellowing', 'pale', 'chlorosis', 'faded', 'light green',
      'old leaves', 'lower leaves', 'stunted', 'slow growth', 'thin',
    ],
    colorHints: { yellow: 2.4, green: 0.4, brown: 0.3 },
    oldGrowth: true,
    lacks: ['Available nitrogen', 'Adequate protein synthesis', 'Chlorophyll production in mature leaves'],
    needs: ['Balanced nitrogen feed (urea, nitrate, or fish emulsion)', 'Organic matter / compost', 'Steady moisture so roots can take N up'],
    protocol: [
      'Confirm it is older leaves first — if young leaves yellow first, look at iron or sulfur instead.',
      'Feed a complete fertilizer with a higher first number (e.g. 3-1-2 ratio for foliage plants).',
      'Water in thoroughly; dry soil blocks uptake even when fertilizer is present.',
      'For containers, flush salts then resume a dilute weekly feed.',
      'Recheck in 7–14 days: new growth should green first.',
    ],
    prevent: ['Regular feeding during active growth', 'Mulch and compost', 'Do not overpot into barren mix'],
    urgency: 'act',
    professional: 'If yellowing races through the whole canopy in days, rule out root rot or gas before adding more N.',
    atlasImage: '/images/plant-yellow.jpg',
  },
  {
    id: 'plant-fe-def',
    name: 'Iron deficiency',
    commonName: 'Interveinal chlorosis of new leaves',
    kingdom: 'plant',
    categories: ['houseplant', 'crop', 'tree', 'ornamental'],
    type: 'deficiency',
    summary:
      'Iron is immobile. New leaves yellow while veins stay a sharp green — a classic “green net on yellow cloth.” Often a pH lockout, not an empty tank.',
    visualSigns: [
      'Youngest leaves yellow with green veins',
      'Newest growth almost white in severe cases',
      'Older leaves remain greener',
      'Common in alkaline or overwatered mixes',
    ],
    keywords: [
      'interveinal', 'veins', 'green veins', 'young leaves', 'new growth',
      'yellow', 'pale', 'white leaves', 'chlorosis', 'alkaline', 'high ph',
    ],
    colorHints: { yellow: 2.2, green: 0.6, white: 0.6 },
    youngGrowth: true,
    lacks: ['Available iron (often locked by high pH)', 'Oxygen at the root if soil is waterlogged'],
    needs: ['Chelated iron (Fe-EDDHA in high pH)', 'Slightly acidic mix (pH 5.5–6.5 for most)', 'Better drainage / less frequent watering'],
    protocol: [
      'Check watering first — soggy roots cannot take iron even if it is in the pot.',
      'Lower pH with rainwater, peat, or a mild acidifier if the mix tests alkaline.',
      'Apply chelated iron as a soil drench; foliar sprays green leaves faster but do not fix the root cause.',
      'Avoid overliming and excess phosphorus, which antagonize iron.',
    ],
    prevent: ['Acid-loving plants in acidic media', 'Never let pots sit in saucers of water', 'Periodic pH checks'],
    urgency: 'act',
    professional: 'Persistent chlorosis on trees in calcareous soil may need trunk injection or soil sulfur by an arborist.',
    atlasImage: '/images/plant-yellow.jpg',
  },
  {
    id: 'plant-mg-def',
    name: 'Magnesium deficiency',
    commonName: 'Interveinal yellowing of older leaves',
    kingdom: 'plant',
    categories: ['houseplant', 'crop', 'ornamental', 'tree'],
    type: 'deficiency',
    summary:
      'Magnesium sits at the heart of chlorophyll. Shortage shows as yellowing between veins on older leaves, often with a Christmas-tree green pattern along the midrib.',
    visualSigns: [
      'Older leaves yellow between veins',
      'Green arrowhead or Christmas-tree pattern along the midrib',
      'Leaf edges may bronze or crisp later',
      'Tomatoes, roses, palms, and citrus are frequent patients',
    ],
    keywords: [
      'magnesium', 'epsom', 'interveinal', 'old leaves', 'yellow between veins',
      'bronze', 'tomato', 'citrus', 'palm',
    ],
    colorHints: { yellow: 2.0, green: 0.5, orange: 0.4 },
    oldGrowth: true,
    mottled: true,
    lacks: ['Magnesium', 'Sometimes potassium balance is off (excess K blocks Mg)'],
    needs: ['Epsom salt drench (magnesium sulfate)', 'Cal-mag if using RO / rainwater', 'Balanced K so it does not outcompete Mg'],
    protocol: [
      'Dissolve 1 tbsp Epsom salt per gallon and drench the root zone; repeat every 2–4 weeks while correcting.',
      'Do not dump extra potassium fertilizer at the same time.',
      'In hydro or RO water, add a dedicated cal-mag supplement.',
      'Necrotic tissue will not re-green — judge success on new and recently affected leaves.',
    ],
    prevent: ['Hard water often supplies Mg; RO users must supplement', 'Avoid one-sided high-K bloom formulas on foliage plants'],
    urgency: 'act',
    professional: 'Soil test if a whole bed shows the pattern — dolomitic lime can correct acidic field soil.',
    atlasImage: '/images/leaf-spots.jpg',
  },
  {
    id: 'plant-k-def',
    name: 'Potassium deficiency',
    commonName: 'Marginal leaf scorch',
    kingdom: 'plant',
    categories: ['houseplant', 'crop', 'tree', 'ornamental'],
    type: 'deficiency',
    summary:
      'Potassium regulates water and stomata. Shortage burns the leaf rim — a brown, crispy margin on older leaves — while the center may stay green.',
    visualSigns: [
      'Brown, scorched edges on older leaves',
      'Yellow halo inside the brown margin',
      'Weak stems, poor fruit quality',
      'Tips look burnt rather than spotted',
    ],
    keywords: [
      'brown edges', 'crispy', 'scorch', 'margins', 'leaf edge', 'burnt tips',
      'yellow halo', 'weak stems', 'old leaves',
    ],
    colorHints: { brown: 2.2, yellow: 1.2, orange: 0.5 },
    edgeBias: true,
    oldGrowth: true,
    lacks: ['Potassium', 'Sometimes consistent watering (drought mimics scorch)'],
    needs: ['Potassium-bearing fertilizer (sulfate of potash, kelp)', 'Even moisture', 'Mulch to buffer drought'],
    protocol: [
      'Distinguish from salt burn and underwatering: those also scorch edges. If the soil is bone dry, water first.',
      'If salts crust the pot, flush with 2–3× pot volume of water, then feed a complete formula.',
      'Use sulfate of potash rather than muriate on sensitive crops.',
      'Fruiting plants (tomato, banana, citrus) are heavy K users during crop load.',
    ],
    prevent: ['Complete fertilizer, not nitrogen-only', 'Mulch and regular watering'],
    urgency: 'act',
    professional: 'Sudden whole-plant wilt with brown edges after heat may be vascular wilt, not a simple K lack.',
    atlasImage: '/images/leaf-spots.jpg',
  },
  {
    id: 'plant-p-def',
    name: 'Phosphorus deficiency',
    commonName: 'Purple or dark, stalled growth',
    kingdom: 'plant',
    categories: ['crop', 'houseplant', 'ornamental'],
    type: 'deficiency',
    summary:
      'Phosphorus shortage stalls energy transfer. Foliage may go unusually dark green, then purple or reddish on undersides, especially in cold soil.',
    visualSigns: [
      'Dark green to purple or reddish leaves',
      'Stunted plants, delayed flowering',
      'Older leaves affected first',
      'Worse in cold, wet soils',
    ],
    keywords: [
      'purple', 'reddish', 'dark green', 'stunted', 'no flowers', 'cold soil',
      'phosphorus', 'underside',
    ],
    colorHints: { purple: 3.0, red: 1.2, green: 0.4 },
    oldGrowth: true,
    lacks: ['Available phosphorus', 'Root warmth (cold soil locks P)'],
    needs: ['Phosphorus fertilizer or bone meal in warm soil', 'Warmer root zone', 'Mycorrhizae in low-P soils'],
    protocol: [
      'Warm the root zone if nights are cold — P uptake collapses below ~15°C.',
      'Do not flood high-P fertilizer onto already purple cold seedlings; wait for warmth.',
      'In containers, use a complete liquid feed once roots are active.',
      'Some varieties (certain coleus, ornamental kale) are naturally purple — match to species.',
    ],
    prevent: ['Do not plant heat-lovers in icy soil', 'Maintain biological soil with compost'],
    urgency: 'watch',
    professional: 'Excess P is a common indoor-plant problem and can lock out iron — do not stack bloom boosters blindly.',
    atlasImage: '/images/greenhouse.jpg',
  },
  {
    id: 'plant-ca-def',
    name: 'Calcium deficiency',
    commonName: 'Tip burn and distorted new growth',
    kingdom: 'plant',
    categories: ['crop', 'houseplant', 'ornamental'],
    type: 'deficiency',
    summary:
      'Calcium builds cell walls and does not move from old leaves. New tips die, cup, or distort; fruit may show blossom-end rot even when the soil has lime.',
    visualSigns: [
      'New growth hooked, cupped, or necrotic at the tip',
      'Blossom-end rot on tomato, pepper, squash',
      'Tip burn on lettuce and brassicas',
      'Weak stems on the newest flush',
    ],
    keywords: [
      'blossom end rot', 'tip burn', 'distorted', 'hooked', 'new growth die',
      'calcium', 'cupped', 'black bottom tomato',
    ],
    colorHints: { brown: 1.4, yellow: 0.6, black: 0.8 },
    youngGrowth: true,
    lacks: ['Calcium delivery to new tissue (often a water-flow problem, not empty soil)', 'Steady transpiration'],
    needs: ['Even watering', 'Calcium nitrate or gypsum if soil truly lacks Ca', 'Airflow so plants transpire'],
    protocol: [
      'Fix boom-and-bust watering first — Ca rides the transpiration stream.',
      'Mulch and keep moisture even during fruit swell.',
      'Foliar calcium can bandage fruit; the real fix is roots and water rhythm.',
      'Do not overdo ammonium nitrogen, which competes with calcium.',
    ],
    prevent: ['Consistent irrigation', 'Avoid wild swings from drought to flood'],
    urgency: 'act',
    professional: 'If growing in RO water, add cal-mag. If soil pH is very low, lime based on a test.',
    atlasImage: '/images/garden.jpg',
  },
  {
    id: 'plant-zn-def',
    name: 'Zinc deficiency',
    commonName: 'Little leaf and rosetting',
    kingdom: 'plant',
    categories: ['crop', 'tree', 'ornamental'],
    type: 'deficiency',
    summary:
      'Zinc shortage shrinks internodes. New leaves come out small, narrow, and bunched (rosette), with striping between veins.',
    visualSigns: [
      'Tiny new leaves (little-leaf)',
      'Short internodes, witches’-broom look',
      'Interveinal striping on young foliage',
      'Common on citrus, pecans, corn, and high-pH soils',
    ],
    keywords: [
      'little leaf', 'small leaves', 'rosette', 'zinc', 'striping', 'bunched',
      'short internodes', 'citrus',
    ],
    colorHints: { yellow: 1.4, green: 0.5 },
    youngGrowth: true,
    lacks: ['Available zinc', 'Often blocked by high phosphorus or high pH'],
    needs: ['Zinc sulfate or chelated zinc', 'Correct pH', 'Ease off excess phosphate'],
    protocol: [
      'Foliar zinc corrects citrus and pecan quickly; soil applications last longer.',
      'Do not apply with a heavy P fertilizer in the same drench.',
      'Confirm species — some cultivars naturally have small leaves.',
    ],
    prevent: ['Balanced micronutrient program on high-pH ground', 'Avoid stacking superphosphate'],
    urgency: 'act',
    professional: 'Orchard zinc is often a foliar winter/spring spray — ask an extension agent for local rates.',
    atlasImage: '/images/greenhouse.jpg',
  },
  {
    id: 'plant-s-def',
    name: 'Sulfur deficiency',
    commonName: 'Uniform pale new growth',
    kingdom: 'plant',
    categories: ['crop', 'houseplant', 'ornamental'],
    type: 'deficiency',
    summary:
      'Sulfur shortage mimics nitrogen but hits young leaves first: the whole new flush turns evenly lime-yellow, not interveinal.',
    visualSigns: [
      'Young leaves uniformly pale yellow',
      'No sharp green vein pattern',
      'Thin, soft growth',
      'More common in sandy, leached, or soilless mixes',
    ],
    keywords: [
      'pale new', 'yellow young', 'sulfur', 'lime green', 'even yellow',
      'new growth pale',
    ],
    colorHints: { yellow: 2.0, green: 0.5 },
    youngGrowth: true,
    lacks: ['Sulfate sulfur'],
    needs: ['Sulfate of potash, Epsom salt, or a complete fertilizer that includes S', 'Organic matter'],
    protocol: [
      'If young leaves are evenly pale (not veined), sulfur or iron is likelier than nitrogen.',
      'Epsom salt supplies both Mg and S — useful when both are lean.',
      'Gypsum adds Ca and S without raising pH.',
    ],
    prevent: ['Complete fertilizers rather than urea-only', 'Compost'],
    urgency: 'watch',
    professional: 'Tissue tests distinguish S from Fe and N when the pattern is ambiguous.',
    atlasImage: '/images/plant-yellow.jpg',
  },
  {
    id: 'plant-overwater',
    name: 'Overwatering / hypoxia',
    commonName: 'Soggy roots, yellow limp leaves',
    kingdom: 'plant',
    categories: ['houseplant', 'ornamental', 'crop'],
    type: 'environment',
    summary:
      'Roots need oxygen. Constant wet mix suffocates them, so leaves yellow and droop even though the pot is heavy. Often the true cause behind “mystery deficiencies.”',
    visualSigns: [
      'Yellowing plus limp, not crispy, leaves',
      'Pot feels heavy; soil smells sour',
      'Edema blisters on undersides',
      'Fungus gnats, mushy stems at soil line',
    ],
    keywords: [
      'overwater', 'soggy', 'wet', 'heavy pot', 'droop', 'limp', 'yellow',
      'gnats', 'sour', 'mushy', 'edema', 'saucer',
    ],
    colorHints: { yellow: 1.6, brown: 0.8, green: 0.4 },
    lacks: ['Oxygen at the root', 'Functional root hairs'],
    needs: ['Dry-down between waterings', 'Faster drainage', 'Possibly a smaller pot or chunkier mix'],
    protocol: [
      'Stop watering. Lift the pot — water only when it is light.',
      'Empty saucers. Improve drainage with perlite, bark, or a terra-cotta pot.',
      'If roots are brown and mushy, unpot, trim rot, and repot into fresh airy mix.',
      'Hold fertilizer until new roots grow — feeding a drowning plant makes it worse.',
    ],
    prevent: ['Chunky mix, drainage holes, water by weight not by calendar'],
    urgency: 'act',
    professional: 'Crown rot on succulents and peace lilies can kill the plant in days — unpot immediately if the stem is soft.',
    atlasImage: '/images/roots.jpg',
  },
  {
    id: 'plant-underwater',
    name: 'Drought stress',
    commonName: 'Crispy margins and wilt',
    kingdom: 'plant',
    categories: ['houseplant', 'crop', 'ornamental', 'tree'],
    type: 'environment',
    summary:
      'When the soil dries past the wilt point, leaves lose turgor, then scorch from the edge and tip. Repeated drought also blocks nutrient flow.',
    visualSigns: [
      'Wilting that recovers after a deep water — until it doesn’t',
      'Crispy brown tips and margins',
      'Dry, pulling-away soil',
      'Leaf drop, especially lower or older leaves',
    ],
    keywords: [
      'dry', 'thirsty', 'crispy', 'wilt', 'underwater', 'bone dry',
      'brown tips', 'curling', 'droop then crispy',
    ],
    colorHints: { brown: 1.8, yellow: 0.8 },
    edgeBias: true,
    lacks: ['Water', 'Continuous nutrient flow'],
    needs: ['Deep, infrequent watering to the full root zone', 'Mulch', 'A pot that matches plant size'],
    protocol: [
      'Water slowly until it drains, then do not drip-feed daily — soak and dry.',
      'If peat has gone hydrophobic, bottom-water for 30–45 minutes.',
      'Trim only fully dead tissue; brown tips can be cut following the leaf shape.',
    ],
    prevent: ['Mulch, consistent schedule, larger soil volume in heat'],
    urgency: 'act',
    professional: 'Trees that wilt in wet soil have a different problem (vascular disease or drowning). Always check soil moisture.',
    atlasImage: '/images/leaf-spots.jpg',
  },
  {
    id: 'plant-powdery',
    name: 'Powdery mildew',
    commonName: 'White flour on the leaf',
    kingdom: 'plant',
    categories: ['houseplant', 'crop', 'ornamental', 'tree'],
    type: 'pathogen',
    summary:
      'A fungal film that looks as if flour was dusted on leaves, often in still, humid air with dry soil. It is superficial at first but starves the leaf of light.',
    visualSigns: [
      'White or gray powder on upper leaf surfaces',
      'Starts as circular patches, then sheets over',
      'Leaves may yellow, distort, or drop',
      'Common on squash, rose, phlox, lilac, grape',
    ],
    keywords: [
      'white powder', 'flour', 'mildew', 'dusty', 'white spots', 'powdery',
      'gray film', 'white coating',
    ],
    colorHints: { white: 3.2, green: 0.4, yellow: 0.4 },
    lacks: ['Airflow', 'Leaf-surface dryness at night', 'Sometimes potassium / silicon resilience'],
    needs: ['Air movement', 'Sulfur, potassium bicarbonate, or horticultural oil sprays', 'Resistant varieties'],
    protocol: [
      'Remove the worst leaves; do not compost if your pile stays cool.',
      'Spray morning: potassium bicarbonate, wettable sulfur, or a labeled biofungicide.',
      'Open spacing, prune inner growth, water the soil not the canopy.',
      'Milk sprays (1:9) can suppress mild cases on edibles.',
    ],
    prevent: ['Sun and airflow', 'Avoid late-day overhead watering', 'Do not crowd plants'],
    urgency: 'act',
    professional: 'On grapes and cucurbits it can ruin a crop — use a labeled rotation if kitchen sprays fail.',
    atlasImage: '/images/powdery.jpg',
  },
  {
    id: 'plant-downy',
    name: 'Downy mildew',
    commonName: 'Angular yellow patches, fuzz beneath',
    kingdom: 'plant',
    categories: ['crop', 'ornamental', 'houseplant'],
    type: 'pathogen',
    summary:
      'Not the same as powdery. Downy mildew paints angular yellow islands on the top of the leaf and a gray-purple fuzz on the underside, thriving in cool wet nights.',
    visualSigns: [
      'Yellow angular patches bounded by veins',
      'Gray, purple, or white fuzz on the underside',
      'Rapid blight in wet weather',
      'Basil, impatiens, lettuce, grapes, cucurbits',
    ],
    keywords: [
      'downy', 'underside fuzz', 'angular', 'yellow patches', 'purple fuzz',
      'wet nights', 'basil',
    ],
    colorHints: { yellow: 1.8, white: 1.0, purple: 0.8, brown: 0.6 },
    mottled: true,
    lacks: ['Dry leaf surfaces', 'Airflow during humid nights'],
    needs: ['Remove infected tissue', 'Keep foliage dry', 'Copper or specific downy fungicides if labeled'],
    protocol: [
      'Inspect the underside — powdery sits on top; downy sporulates below.',
      'Destroy badly hit basil or impatiens; they rarely recover as a crop.',
      'Water at the soil, morning only. Increase spacing.',
    ],
    prevent: ['Resistant cultivars', 'Morning irrigation', 'Greenhouse dehumidification'],
    urgency: 'urgent',
    professional: 'Commercial growers should culture-confirm; downy mildews are host-specific and aggressive.',
    atlasImage: '/images/leaf-spots.jpg',
  },
  {
    id: 'plant-rust',
    name: 'Rust',
    commonName: 'Orange pustules',
    kingdom: 'plant',
    categories: ['crop', 'ornamental', 'tree'],
    type: 'pathogen',
    summary:
      'Rust fungi erupt as rusty, orange, or brown powdery pustules, usually on the underside. Each species has a narrow host list.',
    visualSigns: [
      'Orange, yellow, or brown raised pustules',
      'Powder rubs off on a finger',
      'Yellow spots on the upper surface matching pustules below',
      'Hollyhock, snapdragon, rose, beans, lawns, cedar-apple',
    ],
    keywords: [
      'rust', 'orange spots', 'pustules', 'orange powder', 'rusty',
      'underside spots',
    ],
    colorHints: { orange: 3.2, yellow: 1.0, brown: 0.8 },
    mottled: true,
    lacks: ['Dry foliage', 'Sanitation of infected debris'],
    needs: ['Remove infected leaves', 'Sulfur or labeled rust fungicide', 'Resistant varieties'],
    protocol: [
      'Pick off pustuled leaves and bin them.',
      'Avoid overhead watering. Improve airflow.',
      'For lawn rust, mow, fertilize modestly with N, and water deeply but rarely.',
    ],
    prevent: ['Do not crowd', 'Clean up leaf litter', 'Buy rust-resistant roses and beans'],
    urgency: 'act',
    professional: 'Cedar-apple rust needs both hosts; removing nearby junipers is a landscape-scale decision.',
    atlasImage: '/images/leaf-spots.jpg',
  },
  {
    id: 'plant-blight-early',
    name: 'Early blight / target spot',
    commonName: 'Concentric bullseye lesions',
    kingdom: 'plant',
    categories: ['crop', 'ornamental'],
    type: 'pathogen',
    summary:
      'Classic tomato-potato early blight: brown spots with concentric rings like a target, starting on older leaves and marching upward.',
    visualSigns: [
      'Brown spots with bullseye rings',
      'Yellow halo around lesions',
      'Starts low on the plant',
      'Fruit may get leathery collar rot at the stem end',
    ],
    keywords: [
      'target', 'bullseye', 'concentric', 'rings', 'early blight',
      'tomato spots', 'yellow halo', 'brown spots',
    ],
    colorHints: { brown: 2.2, yellow: 1.2, orange: 0.4 },
    mottled: true,
    oldGrowth: true,
    lacks: ['Leaf dryness', 'Airflow', 'Sometimes potassium and overall vigor'],
    needs: ['Sanitation', 'Mulch to stop soil splash', 'Copper or chlorothalonil-type labeled sprays if pressure is high'],
    protocol: [
      'Strip lower infected leaves. Mulch. Stake and prune for airflow.',
      'Water the soil, never the canopy.',
      'Rotate nightshades 2–3 years if this repeats in a bed.',
    ],
    prevent: ['Mulch, staking, crop rotation', 'Resistant tomato varieties'],
    urgency: 'act',
    professional: 'Do not confuse with late blight, which is water-soaked, greasy, and an emergency.',
    atlasImage: '/images/leaf-spots.jpg',
  },
  {
    id: 'plant-blight-late',
    name: 'Late blight',
    commonName: 'Greasy, fast-moving collapse',
    kingdom: 'plant',
    categories: ['crop'],
    type: 'pathogen',
    summary:
      'Phytophthora infestans — the famine pathogen. Water-soaked, greasy gray-brown lesions race through tomato and potato in cool wet weather. This is urgent.',
    visualSigns: [
      'Large greasy, water-soaked patches',
      'White fuzz at lesion edges in humid weather',
      'Rapid blackening of stems and fruit',
      'Foul collapse of a whole row in days',
    ],
    keywords: [
      'late blight', 'greasy', 'water-soaked', 'collapse', 'blacken',
      'white fuzz edge', 'potato', 'tomato blight',
    ],
    colorHints: { brown: 2.0, black: 1.6, white: 0.6, green: 0.2 },
    lacks: ['Dry weather / protection', 'Certified clean seed potatoes'],
    needs: ['Immediate removal of infected plants', 'Do not compost', 'Protect nearby nightshades'],
    protocol: [
      'Bag and trash (or burn where legal) entire infected plants. Do not put on the compost.',
      'Harvest any remaining healthy potatoes immediately and dry them.',
      'Report outbreaks to local extension if you are in a seed-potato region.',
    ],
    prevent: ['Certified seed', 'Resistant cultivars', 'Never save tubers from a blighted field'],
    urgency: 'urgent',
    professional: 'This is a community pathogen. Contact extension; kitchen sprays will not stop an epidemic.',
    atlasImage: '/images/leaf-spots.jpg',
  },
  {
    id: 'plant-leaf-spot',
    name: 'Bacterial or fungal leaf spot',
    commonName: 'Angular or round necrotic spots',
    kingdom: 'plant',
    categories: ['houseplant', 'crop', 'ornamental', 'tree'],
    type: 'pathogen',
    summary:
      'A broad pattern: discrete brown, black, or tan spots, sometimes with a yellow halo. Bacteria tend to be angular and water-soaked; fungi rounder.',
    visualSigns: [
      'Scattered brown or black spots',
      'Yellow halo or water-soaked edge',
      'Spots may fall out leaving shot-holes',
      'Worse after rain or misting',
    ],
    keywords: [
      'spots', 'lesions', 'dots', 'blotches', 'halo', 'shot hole',
      'black spots', 'brown spots', 'speckles',
    ],
    colorHints: { brown: 2.0, black: 1.2, yellow: 0.8 },
    mottled: true,
    lacks: ['Dry foliage', 'Sanitation'],
    needs: ['Remove spotted leaves', 'Stop misting', 'Copper for bacterial; many fungal spots respond to sanitation alone'],
    protocol: [
      'Cut off the worst leaves with clean shears.',
      'Water the soil only. Increase spacing and airflow.',
      'Wipe tools with alcohol between plants.',
      'If spots are water-soaked and smelly, think bacterial — copper, not oil.',
    ],
    prevent: ['Avoid overhead watering', 'Do not crowd', 'Quarantine new plants'],
    urgency: 'act',
    professional: 'Black spot on rose and bacterial leaf spot on pepper have specific labeled programs if sanitation fails.',
    atlasImage: '/images/leaf-spots.jpg',
  },
  {
    id: 'plant-anthracnose',
    name: 'Anthracnose',
    commonName: 'Sunken dark lesions',
    kingdom: 'plant',
    categories: ['crop', 'tree', 'ornamental'],
    type: 'pathogen',
    summary:
      'Sunken, dark, often wet-looking lesions on leaves, stems, or fruit. Beans, mango, avocado, sycamore, and dogwood are frequent hosts.',
    visualSigns: [
      'Sunken brown-black lesions',
      'Pinkish spore masses in wet weather',
      'Twig dieback on trees',
      'Fruit rot with concentric rings',
    ],
    keywords: [
      'sunken', 'anthracnose', 'dark lesions', 'dieback', 'fruit rot',
      'pink spores',
    ],
    colorHints: { brown: 2.0, black: 1.4, orange: 0.5 },
    lacks: ['Dry canopy', 'Wound protection'],
    needs: ['Prune infected wood in dry weather', 'Sanitation', 'Labeled fungicide on high-value fruit'],
    protocol: [
      'Prune several centimeters below lesions on a dry day.',
      'Rake and destroy fallen leaves on trees that blight every spring.',
      'Avoid working plants when they are wet.',
    ],
    prevent: ['Resistant cultivars', 'Airflow', 'Clean seed'],
    urgency: 'act',
    professional: 'Dogwood and sycamore anthracnose is a landscape diagnosis — an arborist can time sprays.',
    atlasImage: '/images/leaf-spots.jpg',
  },
  {
    id: 'plant-mosaic',
    name: 'Mosaic virus',
    commonName: 'Mottled, blistered, distorted foliage',
    kingdom: 'plant',
    categories: ['crop', 'houseplant', 'ornamental'],
    type: 'pathogen',
    summary:
      'Viruses paint a mosaic of light and dark green, often with blistering, shoe-string leaves, or odd fruit. They are not cured — only contained.',
    visualSigns: [
      'Light/dark green mosaic mottling',
      'Blistered or puckered leaf surface',
      'Distorted, narrow, or fern-like new leaves',
      'Stunting; odd color breaks on flowers or fruit',
    ],
    keywords: [
      'mosaic', 'mottled', 'puckered', 'blistered', 'distorted',
      'virus', 'variegated suddenly', 'shoe string',
    ],
    colorHints: { yellow: 1.4, green: 0.8, white: 0.4 },
    mottled: true,
    lacks: ['A healthy vascular system (virus is systemic)', 'Aphid / thrips hygiene if they are the vector'],
    needs: ['Removal of infected plants in a crop setting', 'Aphid control', 'Clean tools'],
    protocol: [
      'Do not try to fertilize a virus away. Mottling plus distortion is a quarantine flag.',
      'Isolate. If it is a tomato, cucumber, or squash crop, pull the plant.',
      'Wash hands and tools. Control aphids and thrips.',
      'Ornamental mosaic (e.g. some abutilon) is sometimes tolerated as a feature — know the species.',
    ],
    prevent: ['Virus-resistant seed', 'Insect screens', 'Never smoke around tomatoes (TMV)'],
    urgency: 'urgent',
    professional: 'Lab ELISA or PCR confirms. There is no home cure.',
    atlasImage: '/images/plant-yellow.jpg',
  },
  {
    id: 'plant-root-rot',
    name: 'Root / crown rot',
    commonName: 'Wilt in wet soil, brown roots',
    kingdom: 'plant',
    categories: ['houseplant', 'ornamental', 'crop', 'tree'],
    type: 'pathogen',
    summary:
      'Pythium, Phytophthora, Rhizoctonia and kin eat roots. The plant wilts as if thirsty while the pot is wet. Roots are brown, mushy, and bark slips off.',
    visualSigns: [
      'Wilt despite wet soil',
      'Yellow lower leaves, sudden collapse',
      'Brown, smelly, slipping roots',
      'Blackened crown at the soil line',
    ],
    keywords: [
      'root rot', 'wilt wet', 'mushy roots', 'collapse', 'crown rot',
      'smelly soil', 'brown roots', 'damping off',
    ],
    colorHints: { yellow: 1.4, brown: 1.4, black: 0.8 },
    lacks: ['Living roots', 'Oxygen', 'A pathogen-suppressive mix'],
    needs: ['Surgery: trim rot, fresh mix, dry-down', 'Sometimes a labeled fungicide drench on high-value plants'],
    protocol: [
      'Unpot. Wash roots. Cut to white tissue. Dust cuts, repot in sterile airy mix.',
      'Do not water for several days. No fertilizer.',
      'Discard the old soil; clean the pot with a 10% bleach rinse.',
    ],
    prevent: ['Drainage, appropriate pot size, sterile mix for seedlings'],
    urgency: 'urgent',
    professional: 'Landscape Phytophthora on trees and avocados needs a plant pathologist — do not keep planting in the same hole.',
    atlasImage: '/images/roots.jpg',
  },
  {
    id: 'plant-aphids',
    name: 'Aphid infestation',
    commonName: 'Sticky, curled new growth',
    kingdom: 'plant',
    categories: ['houseplant', 'crop', 'ornamental', 'tree'],
    type: 'pest',
    summary:
      'Soft-bodied pear-shaped insects cluster on tender tips, sucking sap, curling leaves, and raining honeydew that grows sooty mold.',
    visualSigns: [
      'Clusters of green, black, or pink insects on tips',
      'Cupped or curled new leaves',
      'Sticky honeydew, ants farming them',
      'Black sooty film on lower leaves',
    ],
    keywords: [
      'aphid', 'sticky', 'honeydew', 'curl', 'cluster', 'ants',
      'sooty', 'bugs on tips', 'green bugs',
    ],
    colorHints: { green: 0.6, black: 0.5, yellow: 0.6, white: 0.3 },
    youngGrowth: true,
    lacks: ['Predator insects', 'Physical removal'],
    needs: ['A strong water blast', 'Insecticidal soap or neem', 'Lady beetles / lacewings outdoors'],
    protocol: [
      'Blast with water, then soap spray to undersides, three passes four days apart.',
      'Wipe houseplant tips with a soapy cloth.',
      'Watch for virus symptoms later — aphids vector mosaics.',
    ],
    prevent: ['Inspect new plants', 'Avoid excess nitrogen which makes sappy tissue'],
    urgency: 'act',
    professional: 'On fruit trees, dormant oil in winter plus summer monitoring beats panic spraying.',
    atlasImage: '/images/pests.jpg',
  },
  {
    id: 'plant-mites',
    name: 'Spider mites',
    commonName: 'Stipple, dust, and fine webbing',
    kingdom: 'plant',
    categories: ['houseplant', 'ornamental', 'crop'],
    type: 'pest',
    summary:
      'Nearly invisible mites sandblast the leaf, leaving a pale stipple, dusty undersides, and eventually silk webbing. Hot, dry rooms are their kingdom.',
    visualSigns: [
      'Fine pale speckles on the upper surface',
      'Dusty bronze look',
      'Silk webbing in severe cases',
      'A tap over white paper shows moving dots',
    ],
    keywords: [
      'mites', 'webbing', 'stipple', 'speckles', 'dusty', 'bronze',
      'tiny spiders', 'dry air',
    ],
    colorHints: { yellow: 1.4, white: 0.8, brown: 0.6, green: 0.4 },
    mottled: true,
    lacks: ['Humidity', 'Leaf cleanliness', 'Predatory mites'],
    needs: ['Repeated wetting of undersides', 'Miticide or insecticidal soap', 'Higher humidity'],
    protocol: [
      'Shower the plant, focusing on undersides. Repeat every 3 days for two weeks.',
      'Soap or horticultural oil, never on a hot plant in full sun.',
      'Isolate. Mites hitchhike on clothes.',
    ],
    prevent: ['Humidity 40%+', 'Occasional leaf showers', 'Do not park plants against hot glass'],
    urgency: 'act',
    professional: 'Greenhouse growers rotate miticides; resistance is common. Predatory mites (P. persimilis) are the elegant fix.',
    atlasImage: '/images/powdery.jpg',
  },
  {
    id: 'plant-sunscorch',
    name: 'Sunscorch / photobleach',
    commonName: 'Bleached patches on the sun side',
    kingdom: 'plant',
    categories: ['houseplant', 'ornamental', 'crop'],
    type: 'environment',
    summary:
      'A sudden increase in light cooks chlorophyll. Patches bleach white, tan, or papery, always on the side facing the glass or the afternoon sun.',
    visualSigns: [
      'Crisp bleached patches, not round spots',
      'Worse on the exposed side',
      'Tissue paper-dry, not wet or fuzzy',
      'History of a move to a brighter window or outdoors',
    ],
    keywords: [
      'sunburn', 'bleach', 'scorch', 'white patch', 'moved outside',
      'too much sun', 'crispy patch', 'window',
    ],
    colorHints: { white: 1.6, brown: 1.2, yellow: 0.8 },
    lacks: ['Acclimation time', 'Partial shade during the hottest hours'],
    needs: ['Gradual hardening-off', 'Sheer curtain or 30% shade cloth', 'Water before heat waves'],
    protocol: [
      'Move out of the blast. Burned tissue will not re-green — cut it for looks once dry.',
      'Harden plants over 7–10 days when moving outdoors.',
    ],
    prevent: ['Never jump a shade plant into full July sun'],
    urgency: 'watch',
    professional: 'If bleach is accompanied by wet lesions, it is not sunburn.',
    atlasImage: '/images/hero-leaf.jpg',
  },
  {
    id: 'plant-edema',
    name: 'Edema',
    commonName: 'Water blisters on the underside',
    kingdom: 'plant',
    categories: ['houseplant', 'ornamental', 'crop'],
    type: 'environment',
    summary:
      'Roots take up water faster than leaves can transpire. Cells burst into corky blisters, often mistaken for pest damage, especially on ivy, peperomia, and tomato.',
    visualSigns: [
      'Raised watery bumps on leaf undersides',
      'Later corky, rust-colored scabs',
      'No insects on a tap test',
      'Follows cloudy, wet, still periods',
    ],
    keywords: [
      'edema', 'oedema', 'blisters', 'bumps underside', 'corky',
      'water spots', 'scabs',
    ],
    colorHints: { brown: 0.8, orange: 0.6, white: 0.5 },
    lacks: ['Transpiration (light + airflow)', 'A drier watering rhythm in low light'],
    needs: ['More light and air', 'Less water on dull days', 'Lower humidity at the leaf if roots are wet'],
    protocol: [
      'Let the mix dry more. Add a fan. Increase light.',
      'Do not scrape the blisters; they cork over.',
    ],
    prevent: ['Match watering to light', 'Airflow in greenhouses'],
    urgency: 'watch',
    professional: 'Chronic edema on succulents often means the mix is too rich and wet.',
    atlasImage: '/images/leaf-spots.jpg',
  },
  {
    id: 'plant-ph-lockout',
    name: 'pH lockout',
    commonName: 'Multiple deficiency signs at once',
    kingdom: 'plant',
    categories: ['houseplant', 'crop', 'ornamental'],
    type: 'environment',
    summary:
      'Nutrients can sit in the pot and still be invisible to the plant if pH is wrong. You see mixed chlorosis, tip burn, and stalled growth despite feeding.',
    visualSigns: [
      'Several deficiency patterns at once',
      'White crust of salts on the soil or pot rim',
      'Burnt tips plus yellow new growth',
      'History of tap water, heavy feed, or no flushing',
    ],
    keywords: [
      'lockout', 'ph', 'salts', 'crust', 'fed but yellow', 'white crust',
      'tip burn and yellow',
    ],
    colorHints: { yellow: 1.4, brown: 1.0, white: 0.6 },
    lacks: ['Correct pH (typically 5.8–6.5 in soilless mix)', 'A flushed root zone'],
    needs: ['Flush with 2–3× pot volume of pH-balanced water', 'Resume dilute complete feed', 'Test runoff pH'],
    protocol: [
      'Flush thoroughly. Measure runoff if you can.',
      'Resume feeding at ¼–½ strength after a few days.',
      'Rainwater or filtered water for sensitive plants.',
    ],
    prevent: ['Periodic leaching', 'Do not stack fertilizers', 'Know your tap water'],
    urgency: 'act',
    professional: 'Hydroponic lockout is diagnosed with a pH/EC meter — guesswork wastes crops.',
    atlasImage: '/images/roots.jpg',
  },
  {
    id: 'animal-flea-allergy',
    name: 'Flea-allergy dermatitis',
    commonName: 'Itch, rump hair loss, scabs',
    kingdom: 'animal',
    categories: ['dog', 'cat', 'small-mammal'],
    type: 'allergy',
    summary:
      'A single flea bite can set off an allergic storm. Dogs chew the rump and tail base; cats overgroom into a moth-eaten coat, often without an obvious flea.',
    visualSigns: [
      'Hair loss and scabs over the rump, tail base, inner thighs',
      'Hot, pepper-like black specks (flea dirt) that bleed red on wet paper',
      'Restlessness, chewing, licking',
      'Cats: tiny scabs along the back (miliary dermatitis)',
    ],
    keywords: [
      'flea', 'itch', 'scratch', 'rump', 'tail', 'scabs', 'hair loss',
      'flea dirt', 'chewing', 'miliary', 'overgroom',
    ],
    colorHints: { red: 1.6, pink: 1.2, black: 0.6, brown: 0.5 },
    lacks: ['Flea control on all pets and the home', 'Skin barrier lipids while inflamed'],
    needs: ['Veterinary flea adulticide (isoxazoline or equivalent)', 'Home treatment', 'Soothing skin care, not a steroid-only approach'],
    protocol: [
      'Treat every pet in the house, not just the itchy one.',
      'Wash bedding hot. Vacuum, then bin the bag.',
      'Do not use dog permethrin products on cats.',
      'See a vet if the skin is open, smelly, or the animal is miserable — infection rides along.',
    ],
    prevent: ['Year-round vet-grade flea prevention', 'Wildlife and carpet control'],
    urgency: 'act',
    professional: 'This is a veterinary diagnosis. Secondary staph infection is common and needs proper meds.',
    atlasImage: '/images/vet-dog.jpg',
  },
  {
    id: 'animal-mange-sarcoptic',
    name: 'Sarcoptic mange (scabies)',
    commonName: 'Intense itch, crusts on elbows and ear edges',
    kingdom: 'animal',
    categories: ['dog', 'livestock', 'small-mammal', 'equine'],
    type: 'parasite',
    summary:
      'Sarcoptes mites tunnel in the skin. Itch is violent. Classic start: ear margins, elbows, hocks. People in the house may get transient itchy bumps.',
    visualSigns: [
      'Crusty ear edges',
      'Red, hairless patches on elbows, chest, belly',
      'Unrelenting itch, worse in warmth',
      'Self-inflicted sores',
    ],
    keywords: [
      'mange', 'scabies', 'ear edges', 'elbows', 'intense itch',
      'crust', 'people itchy', 'fox', 'coyote',
    ],
    colorHints: { red: 1.8, pink: 1.2, brown: 0.8, white: 0.4 },
    lacks: ['A mite-free environment', 'Intact skin barrier'],
    needs: ['Veterinary acaricide (isoxazolines are often used)', 'Isolation from untreated animals', 'Soothing care for crusts'],
    protocol: [
      'This is not a home-diagnosis-and-wait condition — see a veterinarian promptly.',
      'Treat all in-contact dogs. Cats and people usually get a milder, self-limiting rash.',
      'Wash bedding. The mite survives only a few days off the host.',
    ],
    prevent: ['Limit contact with foxes, stray dogs, infested kennels'],
    urgency: 'urgent',
    professional: 'Skin scrapings can be negative even when mites are present. Response to treatment is often the confirmation.',
    atlasImage: '/images/vet-dog.jpg',
  },
  {
    id: 'animal-ringworm',
    name: 'Ringworm (dermatophyte)',
    commonName: 'Circular hairless patches, crusty',
    kingdom: 'animal',
    categories: ['dog', 'cat', 'livestock', 'equine', 'small-mammal'],
    type: 'pathogen',
    summary:
      'A fungus of keratin, not a worm. Round, scaly, hairless patches — especially on the face, ears, and paws. Kittens, calves, and show lambs are classic.',
    visualSigns: [
      'Circular alopecia with scaly gray crust',
      'Broken hairs at the edge',
      'Often face, ears, paws',
      'May glow apple-green under Wood’s lamp (some Microsporum)',
    ],
    keywords: [
      'ringworm', 'circular', 'round patch', 'scaly', 'hairless circle',
      'kitten', 'crusty patch', 'fungus',
    ],
    colorHints: { white: 1.2, red: 0.8, brown: 0.6, pink: 0.6 },
    lacks: ['Intact immunity (young, stressed animals)', 'Environmental decontamination'],
    needs: ['Veterinary antifungal (topical ± oral)', 'Clip and clean lesions', 'Disinfect bedding and brushes'],
    protocol: [
      'See a vet — ringworm is zoonotic. Children and immunocompromised people are at risk.',
      'Do not share grooming tools. Isolate.',
      'Bleach dilutions or labeled veterinary disinfectants on surfaces; one clean is not enough.',
    ],
    prevent: ['Quarantine new animals', 'Good nutrition and low crowding'],
    urgency: 'act',
    professional: 'Culture or PCR confirms. Lime sulfur and oral antifungals are vet-directed, not DIY on cats.',
    atlasImage: '/images/cat.jpg',
  },
  {
    id: 'animal-hotspot',
    name: 'Hot spot (acute moist dermatitis)',
    commonName: 'Sudden wet, painful, spreading sore',
    kingdom: 'animal',
    categories: ['dog'],
    type: 'injury',
    summary:
      'A lick-scratch spiral. A wet, red, foul patch appears in hours, often under a dense coat after swimming or an unnoticed sting.',
    visualSigns: [
      'Wet, red, oozing area that enlarges fast',
      'Hair stuck in a crusted mat',
      'Very painful; dog may snap if touched',
      'Common on cheeks, neck, rump of thick-coated breeds',
    ],
    keywords: [
      'hot spot', 'wet sore', 'oozing', 'sudden wound', 'lick',
      'smelly patch', 'moist dermatitis',
    ],
    colorHints: { red: 2.4, pink: 1.4, brown: 0.6 },
    lacks: ['Air at the skin', 'An end to the itch cycle'],
    needs: ['Clip the coat wide of the lesion', 'Gentle cleanse', 'Veterinary anti-inflammatory and often antibiotic'],
    protocol: [
      'This is painful — a vet should clip and treat. Do not pour alcohol on it.',
      'E-collar so the dog cannot keep licking.',
      'Find the trigger: ear infection, fleas, anal glands, allergy.',
    ],
    prevent: ['Dry coats after swimming', 'Flea control', 'Groom dense undercoats'],
    urgency: 'urgent',
    professional: 'Untreated hot spots excavate large areas overnight. Pain control is not optional.',
    atlasImage: '/images/vet-dog.jpg',
  },
  {
    id: 'animal-atopy',
    name: 'Environmental allergy (atopy)',
    commonName: 'Seasonal itch of paws, face, ears',
    kingdom: 'animal',
    categories: ['dog', 'cat', 'equine'],
    type: 'allergy',
    summary:
      'Pollen, mite, and mold allergies show as feet-licking, face-rubbing, and recurrent ear flares. Skin looks pink, stained, and weary rather than one round lesion.',
    visualSigns: [
      'Salmon-pink paws, saliva-stained fur',
      'Rubbed muzzle and eyes',
      'Recurrent ear yeast',
      'Seasonal or year-round itch without fleas found',
    ],
    keywords: [
      'allergy', 'paws', 'licking feet', 'seasonal', 'ears', 'itchy face',
      'pollen', 'atopy', 'red paws',
    ],
    colorHints: { pink: 2.0, red: 1.4, brown: 0.4 },
    lacks: ['Allergen avoidance (often impossible)', 'Skin barrier lipids', 'A long-term control plan'],
    needs: ['Vet-guided anti-itch plan', 'Omega-3s, frequent bathing with gentle products', 'Ear care'],
    protocol: [
      'Rule out fleas, food, and mites with a veterinarian — atopy is a diagnosis of pattern plus exclusion.',
      'Wipe paws after walks. Use a vet-recommended shampoo, not human products.',
      'Do not chronic-steroid without a plan; newer itch medicines exist.',
    ],
    prevent: ['Year-round parasite control so fleas are not confused with atopy'],
    urgency: 'act',
    professional: 'Dermatology workups (diet trial, cytology, possibly immunotherapy) change quality of life.',
    atlasImage: '/images/vet-dog.jpg',
  },
  {
    id: 'animal-dry-skin',
    name: 'Xerosis / seborrhea',
    commonName: 'Flakes, dull coat, tight skin',
    kingdom: 'animal',
    categories: ['dog', 'cat', 'equine', 'livestock', 'small-mammal'],
    type: 'deficiency',
    summary:
      'Dry, scurfy skin from low humidity, over-bathing, poor fat intake, or endocrine disease. The coat loses sheen; white dander snows on dark fabric.',
    visualSigns: [
      'Dandruff, especially along the back',
      'Dull, brittle coat',
      'Tight, itchy skin without open sores',
      'Worse in winter heating',
    ],
    keywords: [
      'dandruff', 'flakes', 'dry skin', 'dull coat', 'brittle',
      'scurf', 'overbath', 'dry',
    ],
    colorHints: { white: 1.4, neutral: 0.6, brown: 0.3 },
    lacks: ['Essential fatty acids', 'Humidity', 'Sometimes thyroid / other endocrine balance', 'A gentle bathing rhythm'],
    needs: ['Dietary omega-3 (fish oil dosed by a vet)', 'Humidifier', 'Mild oatmeal or ceramide shampoo, then rinse well'],
    protocol: [
      'Stop daily detergent baths. Switch to lukewarm water and a mild veterinary shampoo.',
      'Add vet-approved fish oil. Improve diet quality (complete feed, not table scraps).',
      'If a dog is also lethargic, gaining weight, or losing hair symmetrically, ask about thyroid.',
    ],
    prevent: ['Complete diet', 'Limit baths', 'Indoor humidity 40%'],
    urgency: 'watch',
    professional: 'Seborrhea can be primary or a sign of thyroid, Cushing, or allergy disease.',
    atlasImage: '/images/cat.jpg',
  },
  {
    id: 'animal-zinc-def',
    name: 'Zinc-responsive dermatosis',
    commonName: 'Crusts on nose, eyes, and pressure points',
    kingdom: 'animal',
    categories: ['dog', 'livestock', 'equine'],
    type: 'deficiency',
    summary:
      'Zinc shortage or poor zinc use (common in Arctic breeds and rapidly growing livestock) crusts the mucocutaneous junctions: nose, lips, eyes, and footpads.',
    visualSigns: [
      'Thick crusts around nose, eyes, mouth',
      'Scale on elbows and footpads',
      'Dull coat, poor wound healing',
      'Husky, Malamute, Great Dane; also calves and lambs on high-grain or high-calcium diets',
    ],
    keywords: [
      'zinc', 'crusts nose', 'husky', 'malamute', 'footpads',
      'around eyes', 'scale muzzle', 'poor growth',
    ],
    colorHints: { brown: 1.2, white: 0.8, red: 0.8, pink: 0.6 },
    lacks: ['Available zinc', 'Sometimes a genetic uptake defect', 'Balance vs excess calcium / phytate'],
    needs: ['Veterinary zinc supplementation', 'Diet reformulation', 'Do not home-dose high zinc (toxicity)'],
    protocol: [
      'See a veterinarian — zinc sulfate or methionine is dosed, not guessed.',
      'Review the diet: high-calcium cheap kibble or heavily phytate plant diets bind zinc.',
      'Livestock: check mineral mix; excess calcium from over-limed forage is a classic trap.',
    ],
    prevent: ['Breed-appropriate complete diets', 'Balanced free-choice minerals for stock'],
    urgency: 'act',
    professional: 'Rule out autoimmune crusting diseases (pemphigus) which can look similar.',
    atlasImage: '/images/vet-dog.jpg',
  },
  {
    id: 'animal-protein-def',
    name: 'Protein / energy malnutrition',
    commonName: 'Thin coat, slow healing, muscle loss',
    kingdom: 'animal',
    categories: ['dog', 'cat', 'livestock', 'equine', 'bird', 'small-mammal'],
    type: 'deficiency',
    summary:
      'Hair and feathers are protein. When the ration is thin, the coat goes dull, sheds, and wounds linger. Body condition falls behind the skin signs.',
    visualSigns: [
      'Sparse, faded, brittle coat or feathers',
      'Visible ribs, poor muscling',
      'Slow-growing or overgrown brittle nails / hooves',
      'Young animals fail to thrive',
    ],
    keywords: [
      'thin', 'ribs', 'dull coat', 'not eating', 'poor growth',
      'protein', 'malnourished', 'faded coat', 'feather',
    ],
    colorHints: { brown: 0.6, white: 0.4, yellow: 0.3, neutral: 0.8 },
    lacks: ['High-quality protein', 'Calories', 'Often other micronutrients in the same poor ration'],
    needs: ['A complete, species-appropriate diet', 'Gradual refeeding if starved', 'Parasite check — worms steal protein'],
    protocol: [
      'Weigh and body-condition score. Switch to a complete feed designed for the species and life stage.',
      'Cats need meat protein (taurine). Rabbits need hay first, not muesli. Birds need more than seed.',
      'Deworm on veterinary advice. Dental pain is a common reason horses and rabbits stop eating.',
    ],
    prevent: ['Feed a complete ration', 'Regular weigh-ins', 'Dental care'],
    urgency: 'act',
    professional: 'Crash refeeding can kill a starved animal. A vet should plan calories.',
    atlasImage: '/images/livestock.jpg',
  },
  {
    id: 'animal-pyoderma',
    name: 'Bacterial pyoderma',
    commonName: 'Pustules, collarettes, odor',
    kingdom: 'animal',
    categories: ['dog', 'cat', 'livestock', 'equine'],
    type: 'pathogen',
    summary:
      'Staph and kin love damaged skin. You see pustules, circular peeling collarettes, and a sour odor. It is almost always secondary to allergy, parasites, or moisture.',
    visualSigns: [
      'Pustules and peeling rings (epidermal collarettes)',
      'Moth-eaten coat',
      'Musty or sour smell',
      'Itch plus pain',
    ],
    keywords: [
      'pustules', 'pimples', 'collarette', 'smelly skin', 'infection',
      'pyoderma', 'sores', 'ooze',
    ],
    colorHints: { red: 2.0, pink: 1.4, white: 0.8, yellow: 0.5 },
    lacks: ['An intact skin barrier', 'Control of the primary itch'],
    needs: ['Veterinary cytology and the right antibiotic or topical', 'Treat fleas/allergy underneath'],
    protocol: [
      'Do not start leftover people-antibiotics. See a vet for cytology.',
      'Chlorhexidine baths as directed. E-collar if licking.',
      'Expect to hunt the cause — infection that returns is a clue, not a failure of “stronger cream.”',
    ],
    prevent: ['Flea control, dry skin folds, allergy management'],
    urgency: 'act',
    professional: 'MRSP is real. Culture recurrent cases. Never share farm antibiotics casually.',
    atlasImage: '/images/vet-dog.jpg',
  },
  {
    id: 'animal-yeast',
    name: 'Malassezia yeast dermatitis',
    commonName: 'Greasy, itchy, sweet-smelling skin',
    kingdom: 'animal',
    categories: ['dog', 'cat'],
    type: 'pathogen',
    summary:
      'Yeast blooms in ears, paws, and skin folds. The coat feels greasy, itches fiercely, and smells sweet-rancid, like corn chips.',
    visualSigns: [
      'Greasy, red, thickened skin',
      'Brown staining in ears, nails, paws',
      'Corn-chip or musty odor',
      'Elephant-skin thickening if chronic',
    ],
    keywords: [
      'yeast', 'greasy', 'corn chip', 'musty', 'ears brown',
      'itchy paws', 'smell', 'malassezia',
    ],
    colorHints: { brown: 1.4, red: 1.4, pink: 1.2, orange: 0.4 },
    lacks: ['A dry, ventilated skin fold', 'Control of allergy that created the bloom'],
    needs: ['Antifungal shampoo / wipes (chlorhexidine + miconazole type)', 'Ear cleaner if ears involved', 'Vet if deep or chronic'],
    protocol: [
      'Veterinary cytology confirms yeast vs bacteria — they need different drugs.',
      'Wipe paws and folds daily during a flare.',
      'Fix the allergy or endocrine disease underneath or it returns.',
    ],
    prevent: ['Dry ears after swimming', 'Fold care on wrinkly breeds'],
    urgency: 'act',
    professional: 'Brown ear gunk can also be mites. A vet with a scope saves months of the wrong drops.',
    atlasImage: '/images/vet-dog.jpg',
  },
  {
    id: 'animal-ear-mites',
    name: 'Ear mites',
    commonName: 'Coffee-ground debris, head shaking',
    kingdom: 'animal',
    categories: ['cat', 'dog', 'small-mammal'],
    type: 'parasite',
    summary:
      'Otodectes mites fill the canal with dark, dry, coffee-ground debris. Cats shake, scratch the ear base, and may get a hematoma from the violence of it.',
    visualSigns: [
      'Dark dry crumbly ear wax',
      'Intense ear scratching and head shake',
      'Crusts around the ear opening',
      'Often more than one pet in the home',
    ],
    keywords: [
      'ear mites', 'coffee ground', 'head shake', 'ear scratch',
      'dark wax', 'ear debris', 'kitten',
    ],
    colorHints: { brown: 2.0, black: 1.2, red: 0.6 },
    lacks: ['A mite-free ear canal', 'Treatment of all in-contact animals'],
    needs: ['Veterinary ear mite therapy', 'Gentle cleaning', 'Treat the whole household group'],
    protocol: [
      'Do not jam cotton swabs deep. A vet should look at the drum first.',
      'Treat all cats/dogs/ferrets in the home.',
      'Open wounds on the ear flap need a separate look (hematoma).',
    ],
    prevent: ['Quarantine and check new kittens'],
    urgency: 'act',
    professional: 'Not all dark ear wax is mites — yeast and bacteria mimic it. Cytology matters.',
    atlasImage: '/images/cat.jpg',
  },
  {
    id: 'animal-photosensitivity',
    name: 'Photosensitivity / sunburn',
    commonName: 'Burned unpigmented skin',
    kingdom: 'animal',
    categories: ['livestock', 'equine', 'dog', 'cat'],
    type: 'environment',
    summary:
      'White muzzles, eyelids, and ears cook in strong sun. Livestock may also react after eating phototoxic plants (St. John’s wort, certain clovers) or with liver disease.',
    visualSigns: [
      'Red, then crusted skin only on white or thin-haired areas',
      'Ears, nose, eyelids, udder, back',
      'Pain, head-shy, seeking shade',
      'Livestock: sometimes jaundice if the liver is involved',
    ],
    keywords: [
      'sunburn', 'white nose', 'photosensitive', 'crusty muzzle',
      'pink skin burn', 'shade', 'white ears',
    ],
    colorHints: { red: 2.2, pink: 1.6, brown: 0.6, white: 0.5 },
    lacks: ['Pigment or shade', 'Sometimes a healthy liver', 'A forage free of phototoxic plants'],
    needs: ['Shade and indoor hours', 'Veterinary soothing care', 'Liver workup if livestock are systemically ill'],
    protocol: [
      'Provide shade and consider a UV-safe pet-safe pigmented sunblock on white muzzles (vet-approved).',
      'Livestock with sudden sunburn plus illness need a vet the same day — hepatogenous photosensitivity is a herd problem.',
    ],
    prevent: ['Shade, avoid midday turnout for white-faced stock', 'Know toxic plants in the pasture'],
    urgency: 'act',
    professional: 'Cats with white ears can develop squamous cell carcinoma from chronic sun — early vet checks matter.',
    atlasImage: '/images/horse.jpg',
  },
  {
    id: 'animal-foot-rot',
    name: 'Foot rot / interdigital infection',
    commonName: 'Lame, smelly, split hoof skin',
    kingdom: 'animal',
    categories: ['livestock', 'equine'],
    type: 'pathogen',
    summary:
      'Fusobacterium and kin invade wet, injured interdigital skin. The animal is lame, the cleft is necrotic, and the smell is unforgettable.',
    visualSigns: [
      'Sudden lameness',
      'Swollen, split skin between claws',
      'Foul necrotic odor',
      'Worse in wet muddy lots',
    ],
    keywords: [
      'foot rot', 'lame', 'hoof smell', 'between toes', 'mud',
      'swollen foot', 'sheep foot', 'cattle lame',
    ],
    colorHints: { red: 1.2, brown: 1.4, black: 1.0 },
    lacks: ['Dry standing ground', 'Hoof hygiene', 'Sometimes zinc and biotin for horn quality'],
    needs: ['Veterinary exam and often systemic antibiotics for true foot rot', 'Dry housing', 'Footbaths as directed'],
    protocol: [
      'Isolate lame animals on dry ground. Call a vet or experienced stockperson — this is painful.',
      'Do not pour random caustics into a swollen foot.',
      'Fix the mud. Foot rot is a management disease.',
    ],
    prevent: ['Dry lots, regular hoof trimming, zinc in the mineral mix, quarantine new stock'],
    urgency: 'urgent',
    professional: 'Contagious foot rot in sheep is a flock-level program, not a one-animal cream.',
    atlasImage: '/images/livestock.jpg',
  },
  {
    id: 'animal-bumblefoot',
    name: 'Bumblefoot (pododermatitis)',
    commonName: 'Swollen, scabbed footpad',
    kingdom: 'animal',
    categories: ['bird', 'small-mammal', 'reptile'],
    type: 'injury',
    summary:
      'Pressure, damp bedding, and vitamin A-poor diets inflame the footpad. A dark scab (the bumble) sits over an abscess. Common in overweight birds and rabbits on wire.',
    visualSigns: [
      'Swollen pad with a central dark scab',
      'Limping, sitting more than standing',
      'Red, shiny, or ulcerated plantar surface',
      'Often both feet if the perch or floor is the cause',
    ],
    keywords: [
      'bumblefoot', 'swollen foot', 'scab pad', 'limping bird',
      'rabbit sore hock', 'perch', 'wire floor',
    ],
    colorHints: { red: 1.6, brown: 1.4, black: 1.0, pink: 0.8 },
    lacks: ['Proper perch diameter / solid flooring', 'Vitamin A and weight control', 'Dry, clean bedding'],
    needs: ['Veterinary wound care — do not pop this at home', 'Better husbandry', 'Weight loss if obese'],
    protocol: [
      'See an exotic or poultry vet. Squeezing an abscess can seed a joint infection.',
      'Replace wire floors. Vary perch diameters. Keep bedding dry.',
      'Improve diet: dark leafy greens / proper pellets; seed-only birds are vitamin A starved.',
    ],
    prevent: ['Correct perches, clean dry litter, healthy body weight'],
    urgency: 'act',
    professional: 'Advanced bumblefoot is surgery plus antibiotics. Early redness is a husbandry fix.',
    atlasImage: '/images/bird.jpg',
  },
  {
    id: 'animal-scale-rot',
    name: 'Scale rot / dysecdysis',
    commonName: 'Brown belly scales, stuck shed',
    kingdom: 'animal',
    categories: ['reptile'],
    type: 'environment',
    summary:
      'Too-wet, filthy substrate plus cool temps invite bacteria under belly scales. Stuck eye caps and ragged shed mean humidity and vitamin A are also off.',
    visualSigns: [
      'Brown, red, or blistered ventral scales',
      'Stuck shed, especially toes and eye caps',
      'Lethargy, sitting in the water bowl',
      'Open sores if advanced',
    ],
    keywords: [
      'scale rot', 'stuck shed', 'eye cap', 'blister belly',
      'snake', 'reptile', 'humidity', 'dysecdysis',
    ],
    colorHints: { brown: 1.8, red: 1.2, black: 0.8, white: 0.4 },
    lacks: ['A clean thermal gradient', 'Correct humidity (not swamp, not desert unless it is a desert species)', 'Vitamin A in some insectivore diets'],
    needs: ['Dry clean hospital setup', 'Veterinary antimicrobials if ulcerated', 'Humidity hide for shed, not a soaking wet cage'],
    protocol: [
      'Move to paper-towel husbandry. Check temperatures with a gun thermometer, not the sticker.',
      'Do not peel stuck shed off living tissue. A proper humidity box helps.',
      'Ulcerated belly = vet. This can become septicemia.',
    ],
    prevent: ['Species-correct heat and humidity', 'Clean substrate', 'Varied diet with gut-loaded insects'],
    urgency: 'urgent',
    professional: 'Reptile medicine is specialized. A “wait and see” on scale rot is how snakes are lost.',
    atlasImage: '/images/cat.jpg',
  },
  {
    id: 'animal-lice',
    name: 'Lice',
    commonName: 'Nits, restless rubbing, moth-eaten coat',
    kingdom: 'animal',
    categories: ['livestock', 'equine', 'bird', 'dog', 'cat', 'small-mammal'],
    type: 'parasite',
    summary:
      'Host-specific lice glue nits to hair or feathers. Animals rub, bite, and look moth-eaten, especially in winter crowding. The parasites are visible if you look.',
    visualSigns: [
      'Nits glued to hairs',
      'Restless rubbing, especially neck and tailhead',
      'Patchy hair or feather loss',
      'Visible lice on a parting of the coat',
    ],
    keywords: [
      'lice', 'nits', 'rubbing', 'itchy livestock', 'feather lice',
      'winter itch', 'visible bugs',
    ],
    colorHints: { white: 0.8, brown: 0.8, red: 0.6, neutral: 0.5 },
    lacks: ['Parasite control', 'Space and sunlight', 'Sometimes nutrition (lice love a poor host)'],
    needs: ['Species-appropriate insecticide / ivermectin as labeled and legal', 'Treat the group', 'Clean brushes and housing'],
    protocol: [
      'Identify before spraying — different products for birds vs cattle vs horses vs small pets.',
      'Treat all in-contact animals of that species. Repeat as the label says for nits.',
      'Improve feed; lice explode on thin winter stock.',
    ],
    prevent: ['Do not share brushes between farms', 'Avoid overcrowded dark housing'],
    urgency: 'act',
    professional: 'Some products that are fine on cattle kill horses or goats. Read the label or ask a vet.',
    atlasImage: '/images/livestock.jpg',
  },
  {
    id: 'animal-vitamin-a',
    name: 'Vitamin A deficiency',
    commonName: 'Squinting, poor shed, crusty eyes, dull epithelium',
    kingdom: 'animal',
    categories: ['bird', 'reptile', 'small-mammal', 'livestock', 'cat'],
    type: 'deficiency',
    summary:
      'Vitamin A keeps epithelium honest. Shortage shows as swollen eyes in birds and turtles, night-blind livestock, crusty lids, and endless respiratory niggles.',
    visualSigns: [
      'Swollen or crusted eyelids',
      'Choanal or sinus issues in birds',
      'Stuck shed, mouth rot risk in reptiles',
      'Dull, thickened skin; poor night vision in cattle',
    ],
    keywords: [
      'vitamin a', 'swollen eyes', 'crusty eyes', 'seed only',
      'turtle eyes', 'sinus', 'night blind',
    ],
    colorHints: { red: 0.8, white: 0.8, pink: 0.8, brown: 0.4 },
    lacks: ['Preformed vitamin A or beta-carotene', 'A diet beyond seed / iceberg lettuce / ungut-loaded insects'],
    needs: ['Species-correct diet: dark greens, orange veg, liver in appropriate omnivores, gut-loaded insects', 'Vet dosing — vitamin A is toxic in excess'],
    protocol: [
      'Fix the diet first. Seed-only parrots and iceberg-only turtles are textbook cases.',
      'Do not megadose vitamin A oil at home — hypervitaminosis A peels skin.',
      'Swollen bird or turtle eyes need a vet; they may also be abscessed.',
    ],
    prevent: ['Complete pellets plus vegetables', 'Gut-load feeder insects', 'Green forage for herbivores'],
    urgency: 'act',
    professional: 'Injectable vitamin A is a veterinary tool, not a pantry experiment.',
    atlasImage: '/images/bird.jpg',
  },
]

export const PLANT_CATEGORIES: Condition['categories'][number][] = [
  'houseplant',
  'crop',
  'tree',
  'ornamental',
]

export const ANIMAL_CATEGORIES: Condition['categories'][number][] = [
  'dog',
  'cat',
  'livestock',
  'equine',
  'bird',
  'reptile',
  'small-mammal',
]
